### ISSUE TITLE
Updating screen events error

### ISSUE THREAD

**Issue by LatentDesire** [LotuxPunk/K9#11]
Stacktrace:
	at net.minecraft.inventory.Container.func_184996_a(Container.java:246)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:392)
	at com.vandendaelen.k9.gui.K9Gui.func_73864_a(K9Gui.java:165)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: com.vandendaelen.k9.gui.K9Gui

**Comment by LotuxPunk** [comment]
Hey ! Could you send me the full crash report on Pastebin or Gist ? Thanks !
